In [1]:
import gensim
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler
import random

import numpy as np
import pandas as pd
import torch as th
import os
from collections import Counter
import h5py

from xgboost import XGBClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import roc_auc_score

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.multiclass import OneVsRestClassifier
from xgboost import XGBClassifier
from sklearn.preprocessing import MultiLabelBinarizer

from sklearn.metrics import classification_report

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rc
import pandas as pd
import random

In [13]:
data_df = pd.read_csv("TM_Files/LDA_after_filter/ubicomp08_routines_lda_doc_topic_nan_5-topic_5-doc_5-overlap_2-chunk_1000-num_passes_1-update_every_lda_after_filter_unlabeled.csv")

In [14]:
test_days_list = [3, 1, 7, 2, 6, 5, 4]

In [17]:
sa_acc_list, sa_f1_list, sa_prec_list, sa_rec_list, sa_ba_list, ca_acc_list, ca_f1_list, ca_prec_list, ca_rec_list, ca_ba_list, conf_mat_list = [], [], [], [], [], [], [], [], [], [], []

for fold_idx in range(7):
    
    x_train, y_simple_train, y_complex_train, x_test, y_simple_test, y_complex_test = [], [], [], [], [], []

    test_df = data_df[data_df.day == test_days_list[fold_idx]]

    train_df = data_df[data_df.day != test_days_list[fold_idx]]

    x_train = train_df.iloc[:, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 15, 16]].values
    y_simple_train = train_df.iloc[:, 13].values
    y_complex_train = train_df.iloc[:, 14].values
    x_test = test_df.iloc[:, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 15, 16]].values
    y_simple_test = test_df.iloc[:, 13].values
    y_complex_test = test_df.iloc[:, 14].values
    
    '''
    clf = OneVsRestClassifier(XGBClassifier(n_jobs=-1, max_depth=4))
    clf.fit(x_train, y_simple_train)
    predictions = clf.predict(x_test)
    print("Fold : {}".format(fold_idx))
    print("Simple :")
    print(classification_report(y_simple_test, predictions))
    accuracy = accuracy_score(y_simple_test, predictions)
    print("Accuracy: %.4f" % (accuracy))
    sa_acc_list.append(accuracy)
    f1 = f1_score(y_simple_test, predictions, average='macro')
    print("F1: %.4f" % (f1))
    sa_f1_list.append(f1)
    prec = precision_score(y_simple_test, predictions, average='macro')
    print("Precision: %.4f" % (prec))
    sa_prec_list.append(prec)
    recall = recall_score(y_simple_test, predictions, average='macro')
    print("Recall: %.4f" % (recall))
    sa_rec_list.append(recall)
    ba = balanced_accuracy_score(y_simple_test, predictions)
    print("BA: %.4f" % (ba))
    sa_ba_list.append(ba)
    '''
    clf = OneVsRestClassifier(XGBClassifier(n_jobs=-1, max_depth=4))
    clf.fit(x_train, y_complex_train)
    predictions = clf.predict(x_test)
    print("Complex :")
    print(classification_report(y_complex_test, predictions))
    accuracy = accuracy_score(y_complex_test, predictions)
    print("Accuracy: %.4f" % (accuracy))
    ca_acc_list.append(accuracy)
    f1 = f1_score(y_complex_test, predictions, average='weighted')
    print("F1: %.4f" % (f1))
    ca_f1_list.append(f1)
    prec = precision_score(y_complex_test, predictions, average='weighted')
    print("Precision: %.4f" % (prec))
    ca_prec_list.append(prec)
    recall = recall_score(y_complex_test, predictions, average='weighted')
    print("Recall: %.4f" % (recall ))
    ca_rec_list.append(recall)
    ba = balanced_accuracy_score(y_complex_test, predictions)
    print("BA: %.4f" % (ba))
    ca_ba_list.append(ba)
    
    conf_mat_list.append(confusion_matrix(y_complex_test, predictions, normalize = 'true'))
'''
print("Simple Acc: {}".format(np.mean(sa_acc_list)))
print("Simple F1: {}".format(np.mean(sa_f1_list)))
print("Simple Prec: {}".format(np.mean(sa_prec_list)))
print("Simple Rec: {}".format(np.mean(sa_rec_list)))
print("Simple BA: {}".format(np.mean(sa_ba_list)))
'''
print("Confusion Matrix: {}".format(np.mean(conf_mat_list, axis = 0)*100.))
print("Complex Acc: {}".format(np.mean(ca_acc_list)))
print("Complex F1: {}".format(np.mean(ca_f1_list)))
print("Complex Prec: {}".format(np.mean(ca_prec_list)))
print("Complex Rec: {}".format(np.mean(ca_rec_list)))
print("Complex BA: {}".format(np.mean(ca_ba_list)))

Complex :
              precision    recall  f1-score   support

           1       0.88      1.00      0.93      5453
           2       0.52      0.75      0.61      3911
           3       1.00      0.65      0.79      9567
           4       0.94      0.96      0.95     59954

    accuracy                           0.91     78885
   macro avg       0.84      0.84      0.82     78885
weighted avg       0.92      0.91      0.91     78885

Accuracy: 0.9110
F1: 0.9111
Precision: 0.9229
Recall: 0.9110
BA: 0.8365
Complex :
              precision    recall  f1-score   support

           1       0.78      1.00      0.88       840
           2       0.99      0.72      0.83      4816
           3       0.99      0.50      0.67      7022
           4       0.93      1.00      0.96     57863

    accuracy                           0.93     70541
   macro avg       0.92      0.80      0.83     70541
weighted avg       0.93      0.93      0.92     70541

Accuracy: 0.9299
F1: 0.9216
Precision:

In [18]:
sa_acc_list, sa_f1_list, sa_prec_list, sa_rec_list, sa_ba_list, ca_acc_list, ca_f1_list, ca_prec_list, ca_rec_list, ca_ba_list, conf_mat_list = [], [], [], [], [], [], [], [], [], [], []

for fold_idx in range(7):
    
    x_train, y_simple_train, y_complex_train, x_test, y_simple_test, y_complex_test = [], [], [], [], [], []

    test_df = data_df[data_df.day == test_days_list[fold_idx]]

    train_df = data_df[data_df.day != test_days_list[fold_idx]]

    x_train = train_df.iloc[:, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 15, 16, 19]].values
    y_simple_train = train_df.iloc[:, 13].values
    y_complex_train = train_df.iloc[:, 14].values
    x_test = test_df.iloc[:, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 15, 16, 19]].values
    y_simple_test = test_df.iloc[:, 13].values
    y_complex_test = test_df.iloc[:, 14].values
    
    '''
    clf = OneVsRestClassifier(XGBClassifier(n_jobs=-1, max_depth=4))
    clf.fit(x_train, y_simple_train)
    predictions = clf.predict(x_test)
    print("Fold : {}".format(fold_idx))
    print("Simple :")
    print(classification_report(y_simple_test, predictions))
    accuracy = accuracy_score(y_simple_test, predictions)
    print("Accuracy: %.4f" % (accuracy))
    sa_acc_list.append(accuracy)
    f1 = f1_score(y_simple_test, predictions, average='macro')
    print("F1: %.4f" % (f1))
    sa_f1_list.append(f1)
    prec = precision_score(y_simple_test, predictions, average='macro')
    print("Precision: %.4f" % (prec))
    sa_prec_list.append(prec)
    recall = recall_score(y_simple_test, predictions, average='macro')
    print("Recall: %.4f" % (recall))
    sa_rec_list.append(recall)
    ba = balanced_accuracy_score(y_simple_test, predictions)
    print("BA: %.4f" % (ba))
    sa_ba_list.append(ba)
    '''
    clf = OneVsRestClassifier(XGBClassifier(n_jobs=-1, max_depth=4))
    clf.fit(x_train, y_complex_train)
    predictions = clf.predict(x_test)
    print("Complex :")
    print(classification_report(y_complex_test, predictions))
    accuracy = accuracy_score(y_complex_test, predictions)
    print("Accuracy: %.4f" % (accuracy))
    ca_acc_list.append(accuracy)
    f1 = f1_score(y_complex_test, predictions, average='weighted')
    print("F1: %.4f" % (f1))
    ca_f1_list.append(f1)
    prec = precision_score(y_complex_test, predictions, average='weighted')
    print("Precision: %.4f" % (prec))
    ca_prec_list.append(prec)
    recall = recall_score(y_complex_test, predictions, average='weighted')
    print("Recall: %.4f" % (recall ))
    ca_rec_list.append(recall)
    ba = balanced_accuracy_score(y_complex_test, predictions)
    print("BA: %.4f" % (ba))
    ca_ba_list.append(ba)
    
    conf_mat_list.append(confusion_matrix(y_complex_test, predictions, normalize = 'true'))
'''
print("Simple Acc: {}".format(np.mean(sa_acc_list)))
print("Simple F1: {}".format(np.mean(sa_f1_list)))
print("Simple Prec: {}".format(np.mean(sa_prec_list)))
print("Simple Rec: {}".format(np.mean(sa_rec_list)))
print("Simple BA: {}".format(np.mean(sa_ba_list)))
'''
print("Confusion Matrix: {}".format(np.mean(conf_mat_list, axis = 0)*100.))
print("Complex Acc: {}".format(np.mean(ca_acc_list)))
print("Complex F1: {}".format(np.mean(ca_f1_list)))
print("Complex Prec: {}".format(np.mean(ca_prec_list)))
print("Complex Rec: {}".format(np.mean(ca_rec_list)))
print("Complex BA: {}".format(np.mean(ca_ba_list)))

Complex :
              precision    recall  f1-score   support

           1       0.88      1.00      0.93      5453
           2       0.85      0.75      0.80      3911
           3       1.00      0.72      0.83      9567
           4       0.95      0.99      0.97     59954

    accuracy                           0.95     78885
   macro avg       0.92      0.86      0.88     78885
weighted avg       0.95      0.95      0.94     78885

Accuracy: 0.9465
F1: 0.9438
Precision: 0.9483
Recall: 0.9465
BA: 0.8630
Complex :
              precision    recall  f1-score   support

           1       0.78      1.00      0.88       840
           2       0.98      0.75      0.85      4816
           3       1.00      0.45      0.62      7022
           4       0.92      1.00      0.96     57863

    accuracy                           0.93     70541
   macro avg       0.92      0.80      0.83     70541
weighted avg       0.93      0.93      0.92     70541

Accuracy: 0.9274
F1: 0.9175
Precision:

In [ ]:
# Baseline - Filter Unlabeled - Before LDA - Macro

Complex :
              precision    recall  f1-score   support

           1       0.88      1.00      0.93      5453
           2       0.52      0.75      0.61      3911
           3       1.00      0.65      0.79      9567
           4       0.94      0.96      0.95     59954

    accuracy                           0.91     78885
   macro avg       0.84      0.84      0.82     78885
weighted avg       0.92      0.91      0.91     78885

Accuracy: 0.9110
F1: 0.8205
Precision: 0.8351
Recall: 0.8365
BA: 0.8365
Complex :
              precision    recall  f1-score   support

           1       0.78      1.00      0.88       840
           2       0.99      0.72      0.83      4816
           3       0.99      0.50      0.67      7022
           4       0.93      1.00      0.96     57863

    accuracy                           0.93     70541
   macro avg       0.92      0.80      0.83     70541
weighted avg       0.93      0.93      0.92     70541

Accuracy: 0.9299
F1: 0.8340
Precision: 0.9218
Recall: 0.8041
BA: 0.8041
Complex :
              precision    recall  f1-score   support

           1       1.00      0.02      0.04      4041
           2       0.57      0.97      0.72      5373
           3       0.60      0.97      0.74      4275
           4       0.99      0.95      0.97     61029

    accuracy                           0.90     74718
   macro avg       0.79      0.73      0.62     74718
weighted avg       0.94      0.90      0.89     74718

Accuracy: 0.9043
F1: 0.6165
Precision: 0.7892
Recall: 0.7285
BA: 0.7285
Complex :
              precision    recall  f1-score   support

           1       1.00      0.82      0.90      5345
           2       0.68      0.97      0.80      3374
           3       0.61      1.00      0.76      5341
           4       0.99      0.92      0.95     59103

    accuracy                           0.92     73163
   macro avg       0.82      0.93      0.85     73163
weighted avg       0.95      0.92      0.93     73163

Accuracy: 0.9223
F1: 0.8540
Precision: 0.8205
Recall: 0.9286
BA: 0.9286
Complex :
              precision    recall  f1-score   support

           1       0.42      1.00      0.59      1761
           2       1.00      0.56      0.72      4392
           3       0.93      0.85      0.89      7135
           4       0.98      0.98      0.98     58736

    accuracy                           0.94     72024
   macro avg       0.83      0.85      0.79     72024
weighted avg       0.96      0.94      0.95     72024

Accuracy: 0.9434
F1: 0.7940
Precision: 0.8308
Recall: 0.8488
BA: 0.8488
Complex :
              precision    recall  f1-score   support

           1       0.51      0.90      0.65      4388
           2       0.65      0.92      0.76      4413
           3       0.95      0.89      0.92      7995
           4       0.98      0.90      0.94     60719

    accuracy                           0.90     77515
   macro avg       0.77      0.90      0.82     77515
weighted avg       0.93      0.90      0.91     77515

Accuracy: 0.9008
F1: 0.8178
Precision: 0.7720
Recall: 0.9041
BA: 0.9041
Complex :
              precision    recall  f1-score   support

           1       1.00      0.39      0.56      4092
           2       0.63      0.93      0.75      3729
           3       0.94      0.88      0.91      6296
           4       0.97      0.99      0.98     53562

    accuracy                           0.94     67679
   macro avg       0.89      0.80      0.80     67679
weighted avg       0.95      0.94      0.94     67679

Accuracy: 0.9426
F1: 0.8000
Precision: 0.8861
Recall: 0.7969
BA: 0.7969
Confusion Matrix: [[73.18474069 21.63695594  0.          5.17830336]
 [10.59654408 83.10517177  0.          6.29828415]
 [ 0.          0.         82.08369354 17.91630646]
 [ 0.97867592  1.47281145  1.77767371 95.77083892]]
Complex Acc: 0.9220504642246087
Complex F1: 0.7909635597423775
Complex Prec: 0.8364944886738513
Complex Rec: 0.8353611123070204
Complex BA: 0.8353611123070204

In [ ]:
# Topic - Filter Unlabeled - Before LDA - Macro

Complex :
              precision    recall  f1-score   support

           1       0.88      1.00      0.93      5453
           2       0.85      0.75      0.80      3911
           3       1.00      0.72      0.83      9567
           4       0.95      0.99      0.97     59954

    accuracy                           0.95     78885
   macro avg       0.92      0.86      0.88     78885
weighted avg       0.95      0.95      0.94     78885

Accuracy: 0.9465
F1: 0.8838
Precision: 0.9201
Recall: 0.8630
BA: 0.8630
Complex :
              precision    recall  f1-score   support

           1       0.78      1.00      0.88       840
           2       0.98      0.75      0.85      4816
           3       1.00      0.45      0.62      7022
           4       0.92      1.00      0.96     57863

    accuracy                           0.93     70541
   macro avg       0.92      0.80      0.83     70541
weighted avg       0.93      0.93      0.92     70541

Accuracy: 0.9274
F1: 0.8275
Precision: 0.9208
Recall: 0.8000
BA: 0.8000
Complex :
              precision    recall  f1-score   support

           1       1.00      0.14      0.25      4041
           2       0.60      0.98      0.74      5373
           3       0.60      0.97      0.74      4275
           4       1.00      0.95      0.97     61029

    accuracy                           0.91     74718
   macro avg       0.80      0.76      0.68     74718
weighted avg       0.95      0.91      0.91     74718

Accuracy: 0.9134
F1: 0.6776
Precision: 0.7999
Recall: 0.7621
BA: 0.7621
Complex :
              precision    recall  f1-score   support

           1       1.00      0.75      0.86      5345
           2       0.65      1.00      0.79      3374
           3       0.66      1.00      0.79      5341
           4       0.98      0.93      0.95     59103

    accuracy                           0.92     73163
   macro avg       0.82      0.92      0.85     73163
weighted avg       0.94      0.92      0.93     73163

Accuracy: 0.9221
F1: 0.8472
Precision: 0.8214
Recall: 0.9189
BA: 0.9189
Complex :
              precision    recall  f1-score   support

           1       0.78      1.00      0.88      1761
           2       1.00      0.81      0.90      4392
           3       0.95      0.88      0.91      7135
           4       0.97      0.99      0.98     58736

    accuracy                           0.97     72024
   macro avg       0.93      0.92      0.92     72024
weighted avg       0.97      0.97      0.97     72024

Accuracy: 0.9673
F1: 0.9172
Precision: 0.9259
Recall: 0.9207
BA: 0.9207
Complex :
              precision    recall  f1-score   support

           1       0.88      1.00      0.94      4388
           2       0.82      0.86      0.84      4413
           3       0.96      0.89      0.92      7995
           4       0.98      0.98      0.98     60719

    accuracy                           0.96     77515
   macro avg       0.91      0.93      0.92     77515
weighted avg       0.96      0.96      0.96     77515

Accuracy: 0.9631
F1: 0.9203
Precision: 0.9106
Recall: 0.9326
BA: 0.9326
Complex :
              precision    recall  f1-score   support

           1       1.00      0.29      0.46      4092
           2       0.61      1.00      0.76      3729
           3       0.86      0.91      0.89      6296
           4       0.98      0.98      0.98     53562

    accuracy                           0.93     67679
   macro avg       0.86      0.80      0.77     67679
weighted avg       0.95      0.93      0.93     67679

Accuracy: 0.9350
F1: 0.7698
Precision: 0.8623
Recall: 0.7967
BA: 0.7967
Confusion Matrix: [[73.96960075 21.31864662  0.          4.71175263]
 [ 5.06644973 87.80418262  0.          7.12936766]
 [ 0.          0.         83.33996586 16.66003414]
 [ 0.14003824  0.71752611  1.73756732 97.40486833]]
Complex Acc: 0.9392685578996576
Complex F1: 0.8347810744640344
Complex Prec: 0.880137194049699
Complex Rec: 0.8562965438691666
Complex BA: 0.8562965438691666

In [ ]:
# Baseline - Filter Unlabeled - Macro

Complex :
              precision    recall  f1-score   support

           1       0.88      1.00      0.93      5453
           2       0.52      0.75      0.61      3911
           3       1.00      0.65      0.79      9567
           4       0.94      0.96      0.95     59954

    accuracy                           0.91     78885
   macro avg       0.84      0.84      0.82     78885
weighted avg       0.92      0.91      0.91     78885

Accuracy: 0.9110
F1: 0.8205
Precision: 0.8351
Recall: 0.8365
BA: 0.8365
Complex :
              precision    recall  f1-score   support

           1       0.78      1.00      0.88       840
           2       0.99      0.72      0.83      4816
           3       0.99      0.50      0.67      7022
           4       0.93      1.00      0.96     57863

    accuracy                           0.93     70541
   macro avg       0.92      0.80      0.83     70541
weighted avg       0.93      0.93      0.92     70541

Accuracy: 0.9299
F1: 0.8340
Precision: 0.9218
Recall: 0.8041
BA: 0.8041
Complex :
              precision    recall  f1-score   support

           1       1.00      0.02      0.04      4041
           2       0.57      0.97      0.72      5373
           3       0.60      0.97      0.74      4275
           4       0.99      0.95      0.97     61029

    accuracy                           0.90     74718
   macro avg       0.79      0.73      0.62     74718
weighted avg       0.94      0.90      0.89     74718

Accuracy: 0.9043
F1: 0.6165
Precision: 0.7892
Recall: 0.7285
BA: 0.7285
Complex :
              precision    recall  f1-score   support

           1       1.00      0.82      0.90      5345
           2       0.68      0.97      0.80      3374
           3       0.61      1.00      0.76      5341
           4       0.99      0.92      0.95     59103

    accuracy                           0.92     73163
   macro avg       0.82      0.93      0.85     73163
weighted avg       0.95      0.92      0.93     73163

Accuracy: 0.9223
F1: 0.8540
Precision: 0.8205
Recall: 0.9286
BA: 0.9286
Complex :
              precision    recall  f1-score   support

           1       0.42      1.00      0.59      1761
           2       1.00      0.56      0.72      4392
           3       0.93      0.85      0.89      7135
           4       0.98      0.98      0.98     58736

    accuracy                           0.94     72024
   macro avg       0.83      0.85      0.79     72024
weighted avg       0.96      0.94      0.95     72024

Accuracy: 0.9434
F1: 0.7940
Precision: 0.8308
Recall: 0.8488
BA: 0.8488
Complex :
              precision    recall  f1-score   support

           1       0.51      0.90      0.65      4388
           2       0.65      0.92      0.76      4413
           3       0.95      0.89      0.92      7995
           4       0.98      0.90      0.94     60719

    accuracy                           0.90     77515
   macro avg       0.77      0.90      0.82     77515
weighted avg       0.93      0.90      0.91     77515

Accuracy: 0.9008
F1: 0.8178
Precision: 0.7720
Recall: 0.9041
BA: 0.9041
Complex :
              precision    recall  f1-score   support

           1       1.00      0.39      0.56      4092
           2       0.63      0.93      0.75      3729
           3       0.94      0.88      0.91      6296
           4       0.97      0.99      0.98     53562

    accuracy                           0.94     67679
   macro avg       0.89      0.80      0.80     67679
weighted avg       0.95      0.94      0.94     67679

Accuracy: 0.9426
F1: 0.8000
Precision: 0.8861
Recall: 0.7969
BA: 0.7969
Confusion Matrix: [[73.18474069 21.63695594  0.          5.17830336]
 [10.59654408 83.10517177  0.          6.29828415]
 [ 0.          0.         82.08369354 17.91630646]
 [ 0.97867592  1.47281145  1.77767371 95.77083892]]
Complex Acc: 0.9220504642246087
Complex F1: 0.7909635597423775
Complex Prec: 0.8364944886738513
Complex Rec: 0.8353611123070204
Complex BA: 0.8353611123070204


In [ ]:
# Topic - Filter Unlabeled - Macro

Complex :
              precision    recall  f1-score   support

           1       0.87      1.00      0.93      5453
           2       0.99      0.73      0.84      3911
           3       1.00      0.66      0.80      9567
           4       0.95      1.00      0.97     59954

    accuracy                           0.95     78885
   macro avg       0.95      0.85      0.88     78885
weighted avg       0.95      0.95      0.94     78885

Accuracy: 0.9452
F1: 0.8841
Precision: 0.9511
Recall: 0.8469
BA: 0.8469
Complex :
              precision    recall  f1-score   support

           1       0.60      0.42      0.49       840
           2       0.88      0.80      0.84      4816
           3       1.00      0.49      0.65      7022
           4       0.93      1.00      0.96     57863

    accuracy                           0.93     70541
   macro avg       0.85      0.67      0.74     70541
weighted avg       0.93      0.93      0.92     70541

Accuracy: 0.9274
F1: 0.7365
Precision: 0.8530
Recall: 0.6746
BA: 0.6746
Complex :
              precision    recall  f1-score   support

           1       1.00      0.12      0.21      4041
           2       0.60      0.98      0.74      5373
           3       0.60      0.97      0.74      4275
           4       0.99      0.95      0.97     61029

    accuracy                           0.91     74718
   macro avg       0.80      0.76      0.67     74718
weighted avg       0.94      0.91      0.90     74718

Accuracy: 0.9124
F1: 0.6683
Precision: 0.7994
Recall: 0.7561
BA: 0.7561
Complex :
              precision    recall  f1-score   support

           1       1.00      0.92      0.96      5345
           2       0.80      1.00      0.89      3374
           3       0.66      1.00      0.79      5341
           4       1.00      0.94      0.97     59103

    accuracy                           0.95     73163
   macro avg       0.86      0.97      0.90     73163
weighted avg       0.96      0.95      0.95     73163

Accuracy: 0.9490
F1: 0.9025
Precision: 0.8643
Recall: 0.9650
BA: 0.9650
Complex :
              precision    recall  f1-score   support

           1       0.53      1.00      0.69      1761
           2       1.00      0.75      0.86      4392
           3       0.93      0.80      0.86      7135
           4       0.97      0.98      0.98     58736

    accuracy                           0.95     72024
   macro avg       0.86      0.88      0.85     72024
weighted avg       0.96      0.95      0.95     72024

Accuracy: 0.9508
F1: 0.8463
Precision: 0.8579
Recall: 0.8825
BA: 0.8825
Complex :
              precision    recall  f1-score   support

           1       0.74      0.92      0.82      4388
           2       0.92      0.90      0.91      4413
           3       0.97      0.86      0.91      7995
           4       0.97      0.97      0.97     60719

    accuracy                           0.95     77515
   macro avg       0.90      0.91      0.90     77515
weighted avg       0.95      0.95      0.95     77515

Accuracy: 0.9520
F1: 0.9035
Precision: 0.8999
Recall: 0.9133
BA: 0.9133
Complex :
              precision    recall  f1-score   support

           1       1.00      0.35      0.52      4092
           2       0.63      0.99      0.77      3729
           3       0.86      0.95      0.90      6296
           4       0.98      0.98      0.98     53562

    accuracy                           0.94     67679
   macro avg       0.87      0.82      0.79     67679
weighted avg       0.95      0.94      0.94     67679

Accuracy: 0.9407
F1: 0.7924
Precision: 0.8673
Recall: 0.8180
BA: 0.8180
Confusion Matrix: [[67.37373952 29.24652629  0.          3.37973419]
 [ 7.45602494 87.82128949  0.          4.72268557]
 [ 0.          0.         81.84251526 18.15748474]
 [ 0.42631368  0.22067354  1.7421876  97.61082518]]
Complex Acc: 0.9396423530115581
Complex F1: 0.8190814621479179
Complex Prec: 0.8704354953482829
Complex Rec: 0.8366209236268715
Complex BA: 0.8366209236268715

In [ ]:
#Baseline - Filter Unlabeled - Weighted

Complex :
              precision    recall  f1-score   support

           1       0.88      1.00      0.93      5453
           2       0.52      0.75      0.61      3911
           3       1.00      0.65      0.79      9567
           4       0.94      0.96      0.95     59954

    accuracy                           0.91     78885
   macro avg       0.84      0.84      0.82     78885
weighted avg       0.92      0.91      0.91     78885

Accuracy: 0.9110
F1: 0.9111
Precision: 0.9229
Recall: 0.9110
BA: 0.8365
Complex :
              precision    recall  f1-score   support

           1       0.78      1.00      0.88       840
           2       0.99      0.72      0.83      4816
           3       0.99      0.50      0.67      7022
           4       0.93      1.00      0.96     57863

    accuracy                           0.93     70541
   macro avg       0.92      0.80      0.83     70541
weighted avg       0.93      0.93      0.92     70541

Accuracy: 0.9299
F1: 0.9216
Precision: 0.9347
Recall: 0.9299
BA: 0.8041
Complex :
              precision    recall  f1-score   support

           1       1.00      0.02      0.04      4041
           2       0.57      0.97      0.72      5373
           3       0.60      0.97      0.74      4275
           4       0.99      0.95      0.97     61029

    accuracy                           0.90     74718
   macro avg       0.79      0.73      0.62     74718
weighted avg       0.94      0.90      0.89     74718

Accuracy: 0.9043
F1: 0.8903
Precision: 0.9408
Recall: 0.9043
BA: 0.7285
Complex :
              precision    recall  f1-score   support

           1       1.00      0.82      0.90      5345
           2       0.68      0.97      0.80      3374
           3       0.61      1.00      0.76      5341
           4       0.99      0.92      0.95     59103

    accuracy                           0.92     73163
   macro avg       0.82      0.93      0.85     73163
weighted avg       0.95      0.92      0.93     73163

Accuracy: 0.9223
F1: 0.9279
Precision: 0.9457
Recall: 0.9223
BA: 0.9286
Complex :
              precision    recall  f1-score   support

           1       0.42      1.00      0.59      1761
           2       1.00      0.56      0.72      4392
           3       0.93      0.85      0.89      7135
           4       0.98      0.98      0.98     58736

    accuracy                           0.94     72024
   macro avg       0.83      0.85      0.79     72024
weighted avg       0.96      0.94      0.95     72024

Accuracy: 0.9434
F1: 0.9462
Precision: 0.9628
Recall: 0.9434
BA: 0.8488
Complex :
              precision    recall  f1-score   support

           1       0.51      0.90      0.65      4388
           2       0.65      0.92      0.76      4413
           3       0.95      0.89      0.92      7995
           4       0.98      0.90      0.94     60719

    accuracy                           0.90     77515
   macro avg       0.77      0.90      0.82     77515
weighted avg       0.93      0.90      0.91     77515

Accuracy: 0.9008
F1: 0.9092
Precision: 0.9291
Recall: 0.9008
BA: 0.9041
Complex :
              precision    recall  f1-score   support

           1       1.00      0.39      0.56      4092
           2       0.63      0.93      0.75      3729
           3       0.94      0.88      0.91      6296
           4       0.97      0.99      0.98     53562

    accuracy                           0.94     67679
   macro avg       0.89      0.80      0.80     67679
weighted avg       0.95      0.94      0.94     67679

Accuracy: 0.9426
F1: 0.9375
Precision: 0.9524
Recall: 0.9426
BA: 0.7969
Confusion Matrix: [[73.18474069 21.63695594  0.          5.17830336]
 [10.59654408 83.10517177  0.          6.29828415]
 [ 0.          0.         82.08369354 17.91630646]
 [ 0.97867592  1.47281145  1.77767371 95.77083892]]
Complex Acc: 0.9220504642246087
Complex F1: 0.9205541701799024
Complex Prec: 0.9412052765703092
Complex Rec: 0.9220504642246087
Complex BA: 0.8353611123070204


In [ ]:
# Topics - Filter Unlabeled - Weighted

Complex :
              precision    recall  f1-score   support

           1       0.87      1.00      0.93      5453
           2       0.99      0.73      0.84      3911
           3       1.00      0.66      0.80      9567
           4       0.95      1.00      0.97     59954

    accuracy                           0.95     78885
   macro avg       0.95      0.85      0.88     78885
weighted avg       0.95      0.95      0.94     78885

Accuracy: 0.9452
F1: 0.9410
Precision: 0.9489
Recall: 0.9452
BA: 0.8469
Complex :
              precision    recall  f1-score   support

           1       0.60      0.42      0.49       840
           2       0.88      0.80      0.84      4816
           3       1.00      0.49      0.65      7022
           4       0.93      1.00      0.96     57863

    accuracy                           0.93     70541
   macro avg       0.85      0.67      0.74     70541
weighted avg       0.93      0.93      0.92     70541

Accuracy: 0.9274
F1: 0.9182
Precision: 0.9294
Recall: 0.9274
BA: 0.6746
Complex :
              precision    recall  f1-score   support

           1       1.00      0.12      0.21      4041
           2       0.60      0.98      0.74      5373
           3       0.60      0.97      0.74      4275
           4       0.99      0.95      0.97     61029

    accuracy                           0.91     74718
   macro avg       0.80      0.76      0.67     74718
weighted avg       0.94      0.91      0.90     74718

Accuracy: 0.9124
F1: 0.9034
Precision: 0.9442
Recall: 0.9124
BA: 0.7561
Complex :
              precision    recall  f1-score   support

           1       1.00      0.92      0.96      5345
           2       0.80      1.00      0.89      3374
           3       0.66      1.00      0.79      5341
           4       1.00      0.94      0.97     59103

    accuracy                           0.95     73163
   macro avg       0.86      0.97      0.90     73163
weighted avg       0.96      0.95      0.95     73163

Accuracy: 0.9490
F1: 0.9528
Precision: 0.9642
Recall: 0.9490
BA: 0.9650
Complex :
              precision    recall  f1-score   support

           1       0.53      1.00      0.69      1761
           2       1.00      0.75      0.86      4392
           3       0.93      0.80      0.86      7135
           4       0.97      0.98      0.98     58736

    accuracy                           0.95     72024
   macro avg       0.86      0.88      0.85     72024
weighted avg       0.96      0.95      0.95     72024

Accuracy: 0.9508
F1: 0.9522
Precision: 0.9603
Recall: 0.9508
BA: 0.8825
Complex :
              precision    recall  f1-score   support

           1       0.74      0.92      0.82      4388
           2       0.92      0.90      0.91      4413
           3       0.97      0.86      0.91      7995
           4       0.97      0.97      0.97     60719

    accuracy                           0.95     77515
   macro avg       0.90      0.91      0.90     77515
weighted avg       0.95      0.95      0.95     77515

Accuracy: 0.9520
F1: 0.9526
Precision: 0.9549
Recall: 0.9520
BA: 0.9133
Complex :
              precision    recall  f1-score   support

           1       1.00      0.35      0.52      4092
           2       0.63      0.99      0.77      3729
           3       0.86      0.95      0.90      6296
           4       0.98      0.98      0.98     53562

    accuracy                           0.94     67679
   macro avg       0.87      0.82      0.79     67679
weighted avg       0.95      0.94      0.94     67679

Accuracy: 0.9407
F1: 0.9354
Precision: 0.9541
Recall: 0.9407
BA: 0.8180
Confusion Matrix: [[67.37373952 29.24652629  0.          3.37973419]
 [ 7.45602494 87.82128949  0.          4.72268557]
 [ 0.          0.         81.84251526 18.15748474]
 [ 0.42631368  0.22067354  1.7421876  97.61082518]]
Complex Acc: 0.9396423530115581
Complex F1: 0.9364987456236034
Complex Prec: 0.9508580063851261
Complex Rec: 0.9396423530115581
Complex BA: 0.8366209236268715

In [ ]:
Baseline - Macro

Complex Acc: 0.9203696989594649
Complex F1: 0.7897433213579507
Complex Prec: 0.8349865050879524
Complex Rec: 0.8355512700601915
Complex BA: 0.8355512700601915

In [ ]:
Topics - Macro

Complex Acc: 0.9402341075305143
Complex F1: 0.8223091422913856
Complex Prec: 0.8742432646570297
Complex Rec: 0.8447510268790231
Complex BA: 0.8447510268790231

In [ ]:
Baseline - Weighted

Complex Acc: 0.9203696989594649
Complex F1: 0.9193176234941836
Complex Prec: 0.9406677464804877
Complex Rec: 0.920369698959464
Complex BA: 0.8355512700601915

In [ ]:
Topics - Weighted

Complex Acc: 0.9402341075305143
Complex F1: 0.9367450033670839
Complex Prec: 0.9521028856384192
Complex Rec: 0.9402341075305143
Complex BA: 0.8447510268790231